export const CP_LIST_REQUEST = 'CP_LIST_REQUEST'
export const CP_LIST_SUCCESS = 'CP_LIST_SUCCESS'
export const CP_LIST_FAIL = 'CP_LIST_FAIL'

export const CP_DETAILES_REQUEST = 'CP_DETAILES_REQUEST'
export const CP_DETAILES_SUCCESS = 'CP_DETAILES_SUCCESS'
export const CP_DETAILES_FAIL = 'CP_DETAILES_FAIL'

export const CP_CREATE_REQUEST = 'CP_CREATE_REQUEST'
export const CP_CREATE_SUCCESS = 'CP_CREATE_SUCCESS'
export const CP_CREATE_FAIL = 'CP_CREATE_FAIL'

export const CP_UPDATE_REQUEST = 'CP_UPDATE_REQUEST'
export const CP_UPDATE_SUCCESS = 'CP_UPDATE_SUCCESS'
export const CP_UPDATE_FAIL = 'CP_UPDATE_FAIL'

export const CP_DELETE_CST_REQUEST = 'CP_DELETE_CST_REQUEST'
export const CP_DELETE_CST_SUCCESS = 'CP_DELETE_CST_SUCCESS'
export const CP_DELETE_CST_FAIL = 'CP_DELETE_CST_FAIL'

export const CP_DELETE_CAL_REQUEST = 'CP_DELETE_CAL_REQUEST'
export const CP_DELETE_CAL_SUCCESS = 'CP_DELETE_CAL_SUCCESS'
export const CP_DELETE_CAL_FAIL = 'CP_DELETE_CAL_FAIL'

export const CP_LIST_SORTEDBY_CP_ID = 'CP_LIST_SORTEDBY_CP_ID'
export const CP_LIST_SORTEDBY_DATE = 'CP_LIST_SORTEDBY_DATE'
export const CP_LIST_SORTEDBY_CP_ST = 'CP_LIST_SORTEDBY_CP_ST'
export const CP_LIST_SORTEDBY_TZ_ID = 'CP_LIST_SORTEDBY_TZ_ID'
export const CP_LIST_SORTEDBY_ORG = 'CP_LIST_SORTEDBY_ORG'
export const CP_LIST_SORT_FAIL = 'CP_LIST_SORT_FAIL'
export const CP_LIST_SORT_SUCCESS = 'CP_LIST_SORT_SUCCESS'

export const DOWN_CP_DOC_REQUEST = 'DOWN_CP_DOC_REQUEST'
export const DOWN_CP_DOC_SUCCESS = 'DOWN_CP_DOC_SUCCESS'
export const DOWN_CP_DOC_FAIL = 'DOWN_CP_DOC_FAIL'