export const ORG_LIST_REQUEST = 'ORG_LIST_REQUEST'
export const ORG_LIST_SORTEDBY_NAME = 'ORG_LIST_SORTEDBY_NAME'
export const ORG_LIST_SORTEDBY_GROUP = 'ORG_LIST_SORTEDBY_GROUP'
export const ORG_LIST_SORTEDBY_SPEC = 'ORG_LIST_SORTEDBY_SPEC'
export const ORG_LIST_SORTEDBY_COUNTRY = 'ORG_LIST_SORTEDBY_COUNTRY'
export const ORG_LIST_SORT_FAIL = 'ORG_LIST_SORT_FAIL'
export const ORG_LIST_SUCCESS = 'ORG_LIST_SUCCESS'
export const ORG_LIST_FAIL = 'ORG_LIST_FAIL'

export const ORG_UPDATE_REQUEST = 'ORG_UPDATE_REQUEST'
export const ORG_UPDATE_SUCCESS = 'ORG_UPDATE_SUCCESS'
export const ORG_UPDATE_FAIL = 'ORG_UPDATE_FAIL'


export const ORG_REQUEST = 'ORG_REQUEST'
export const ORG_SUCCESS = 'ORG_SUCCESS'
export const ORG_FAIL = 'ORG_FAIL'


export const ADD_ORG_REQUEST = 'ADD_ORG_REQUEST'
export const ADD_ORG_SUCCESS = 'ADD_ORG_SUCCESS'
export const ADD_ORG_FAIL = 'ADD_ORG_FAIL'
