export const SELECT_ALL_REQUEST = 'SELECT_ALL_REQUEST'
export const SELECT_ALL_SUCCESS = 'SELECT_ALL_SUCCESS'
export const SELECT_ALL_FAIL = 'SELECT_ALL_FAIL'

export const SELECT_SPECS_REQUEST = 'SELECT_SPECS_REQUEST'
export const SELECT_SPECS_SUCCESS = 'SELECT_SPECS_SUCCESS'
export const SELECT_SPECS_FAIL = 'SELECT_SPECS_FAIL'