export const TENDER_LIST_REQUEST = 'TENDER_LIST_REQUEST'
export const TENDER_LIST_SUCCESS = 'TENDER_LIST_SUCCESS'
export const TENDER_LIST_FAIL = 'TENDER_LIST_FAIL'

export const TENDER_REQUEST = 'TENDER_REQUEST'
export const TENDER_SUCCESS = 'TENDER_SUCCESS'
export const TENDER_FAIL = 'TENDER_FAIL'

export const FULLCOSTS_REQUEST = 'FULLCOSTS_REQUEST'
export const FULLCOSTS_SUCCESS = 'FULLCOSTS_SUCCESS'
export const FULLCOSTS_FAIL = 'FULLCOSTS_FAIL'