export const TZ_LIST_REQUEST = 'TZ_LIST_REQUEST'
export const TZ_LIST_SUCCESS = 'TZ_LIST_SUCCESS'
export const TZ_LIST_FAIL = 'TZ_LIST_FAIL'

export const TZ_DETAILS_REQUEST = 'TZ_DETAILS_REQUEST'
export const TZ_DETAILS_SUCCESS = 'TZ_DETAILS_SUCCESS'
export const TZ_DETAILS_FAIL = 'TZ_DETAILS_FAIL'

export const TZ_CREATE_REQUEST = 'TZ_CREATE_REQUEST'
export const TZ_CREATE_SUCCESS = 'TZ_CREATE_SUCCESS'
export const TZ_CREATE_FAIL = 'TZ_CREATE_FAIL'

export const TZ_DELETE_CST_REQUEST = 'TZ_DELETE_CST_REQUEST'
export const TZ_DELETE_CST_SUCCESS = 'TZ_DELETE_CST_SUCCESS'
export const TZ_DELETE_CST_FAIL = 'TZ_DELETE_CST_FAIL'

export const TZ_DELETE_CAL_REQUEST = 'TZ_DELETE_CAL_REQUEST'
export const TZ_DELETE_CAL_SUCCESS = 'TZ_DELETE_CAL_SUCCESS'
export const TZ_DELETE_CAL_FAIL = 'TZ_DELETE_CAL_FAIL'

export const TZ_UPDATE_REQUEST = 'TZ_UPDATE_REQUEST'
export const TZ_UPDATE_SUCCESS = 'TZ_UPDATE_SUCCESS'
export const TZ_UPDATE_FAIL = 'TZ_UPDATE_FAIL'

export const TZ_LIST_SORTEDBY_TZ_ID = 'TZ_LIST_SORTEDBY_TZ_ID'
export const TZ_LIST_SORTEDBY_DATE = 'TZ_LIST_SORTEDBY_DATE'
export const TZ_LIST_SORTEDBY_CLIENT = 'TZ_LIST_SORTEDBY_CLIENT'
export const TZ_LIST_SORTEDBY_END_DATE = 'TZ_LIST_SORTEDBY_END_DATE'
export const TZ_LIST_SORTEDBY_STATUS = 'TZ_LIST_SORTEDBY_STATUS'
export const TZ_LIST_SORT_FAIL = 'TZ_LIST_SORT_FAIL'
export const TZ_LIST_SORT_SUCCESS = 'TZ_LIST_SORT_SUCCESS'

export const TZ_FILE_UPLOAD_REQUEST = 'TZ_FILE_UPLOAD_REQUEST'
export const TZ_FILE_UPLOAD_SUCCESS = 'TZ_FILE_UPLOAD_SUCCESS'
export const TZ_FILE_UPLOAD_FAIL = 'TZ_FILE_UPLOAD_FAIL'

export const DOWN_TZ_DOC_REQUEST = 'DOWN_TZ_DOC_REQUEST'
export const DOWN_TZ_DOC_SUCCESS = 'DOWN_TZ_DOC_SUCCESS'
export const DOWN_TZ_DOC_FAIL = 'DOWN_TZ_DOC_FAIL'