export const TZ_LIST_REQUEST = 'TZ_LIST_REQUEST'
export const TZ_LIST_SUCCESS = 'TZ_LIST_SUCCESS'
export const TZ_LIST_FAIL = 'TZ_LIST_FAIL'

export const TZ_DETAILS_REQUEST = 'TZ_DETAILS_REQUEST'
export const TZ_DETAILS_SUCCESS = 'TZ_DETAILS_SUCCESS'
export const TZ_DETAILS_FAIL = 'TZ_DETAILS_FAIL'

export const TZ_CREATE_REQUEST = 'TZ_CREATE_REQUEST'
export const TZ_CREATE_SUCCESS = 'TZ_CREATE_SUCCESS'
export const TZ_CREATE_FAIL = 'TZ_CREATE_FAIL'

export const TZ_DELETE_CST_REQUEST = 'TZ_DELETE_CST_REQUEST'
export const TZ_DELETE_CST_SUCCESS = 'TZ_DELETE_CST_SUCCESS'
export const TZ_DELETE_CST_FAIL = 'TZ_DELETE_CST_FAIL'

export const TZ_DELETE_CAL_REQUEST = 'TZ_DELETE_CAL_REQUEST'
export const TZ_DELETE_CAL_SUCCESS = 'TZ_DELETE_CAL_SUCCESS'
export const TZ_DELETE_CAL_FAIL = 'TZ_DELETE_CAL_FAIL'

export const TZ_UPDATE_REQUEST = 'TZ_UPDATE_REQUEST'
export const TZ_UPDATE_SUCCESS = 'TZ_UPDATE_SUCCESS'
export const TZ_UPDATE_FAIL = 'TZ_UPDATE_FAIL'